=== EDACC/edacc_api/src/parametergraph.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="parameterspace" type="parameterGraph"/>

  <xs:complexType name="parameterGraph">
    <xs:sequence>
      <xs:element name="startNode" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="nodes" type="node" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="parameters" type="parameter" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="edges" type="edge" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="andNode">
    <xs:complexContent>
      <xs:extension base="node">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="node" abstract="true">
    <xs:sequence>
      <xs:element name="domain" type="domain" minOccurs="0"/>
      <xs:element name="id" type="xs:ID" minOccurs="0"/>
      <xs:element name="parameter" type="xs:IDREF" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="domain" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="categoricalDomain">
    <xs:complexContent>
      <xs:extension base="domain">
        <xs:sequence>
          <xs:element name="categories" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="flagDomain">
    <xs:complexContent>
      <xs:extension base="domain">
        <xs:sequence>
          <xs:element name="values" type="flags" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="integerDomain">
    <xs:complexContent>
      <xs:extension base="domain">
        <xs:sequence>
          <xs:element name="high" type="xs:int" minOccurs="0"/>
          <xs:element name="low" type="xs:int" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="mixedDomain">
    <xs:complexContent>
      <xs:extension base="domain">
        <xs:sequence>
          <xs:element name="domains" type="domain" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="optionalDomain">
    <xs:complexContent>
      <xs:extension base="domain">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="realDomain">
    <xs:complexContent>
      <xs:extension base="domain">
        <xs:sequence>
          <xs:element name="high" type="xs:double" minOccurs="0"/>
          <xs:element name="low" type="xs:double" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="parameter">
    <xs:sequence>
      <xs:element name="domain" type="domain" minOccurs="0"/>
      <xs:element name="name" type="xs:ID" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="orNode">
    <xs:complexContent>
      <xs:extension base="node">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="edge">
    <xs:sequence>
      <xs:element name="group" type="xs:int"/>
      <xs:element name="source" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="target" type="xs:IDREF" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="flags">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ON"/>
      <xs:enumeration value="OFF"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== EDACC/edacc_api/src/edacc/parameterspace/test/sparrow_parameterspace.xml
<?xml version="1.0" encoding="UTF-8"?>
<parameterspace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="parametergraph.xsd">
	<startNode>startnode</startNode>
	<nodes xsi:type="andNode">
		<id>startnode</id>
	</nodes>
	<nodes xsi:type="orNode">
		<id>c1_node</id>
		<parameter>c1</parameter>
		<domain xsi:type="integerDomain">
			<high>50</high>
			<low>0</low>
		</domain>
	</nodes>
	<nodes xsi:type="andNode">
		<id>c1_vals</id>
		<parameter>c1</parameter>
		<domain xsi:type="integerDomain">
			<high>50</high>
			<low>0</low>
		</domain>
	</nodes>
	<nodes xsi:type="orNode">
		<id>c2_node</id>
		<parameter>c2</parameter>
		<domain xsi:type="integerDomain">
			<high>50</high>
			<low>0</low>
		</domain>
	</nodes>
	<nodes xsi:type="andNode">
		<id>c2_vals</id>
		<parameter>c2</parameter>
		<domain xsi:type="integerDomain">
			<high>50</high>
			<low>0</low>
		</domain>
	</nodes>
	<nodes xsi:type="orNode">
		<id>c3_node</id>
		<parameter>c3</parameter>
		<domain xsi:type="integerDomain">
			<high>30</high>
			<low>10</low>
		</domain>
	</nodes>
	<nodes xsi:type="andNode">
		<id>c3_vals</id>
		<parameter>c3</parameter>
		<domain xsi:type="integerDomain">
			<high>30</high>
			<low>10</low>
		</domain>
	</nodes>
	<nodes xsi:type="orNode">
		<id>ps_node</id>
		<parameter>ps</parameter>
		<domain xsi:type="realDomain">
			<high>1.0</high>
			<low>0.0</low>
		</domain>
	</nodes>
	<nodes xsi:type="andNode">
		<id>ps_vals</id>
		<parameter>ps</parameter>
		<domain xsi:type="realDomain">
			<high>1.0</high>
			<low>0.0</low>
		</domain>
	</nodes>
	
	
	
	<parameters>
		<domain xsi:type="integerDomain">
			<high>50</high>
			<low>0</low>
		</domain>
		<name>c1</name>
	</parameters>
	
	<parameters>
	
		<domain xsi:type="integerDomain">
			<high>50</high>
			<low>0</low>
		</domain>
		<name>c2</name>
	</parameters>
	
	<parameters>
		<domain xsi:type="integerDomain">
			<high>30</high>
			<low>10</low>
		</domain>
		<name>c3</name>
	</parameters>
	
	<parameters>
		<domain xsi:type="realDomain">
			<high>1.0</high>
			<low>0.0</low>
		</domain>
		<name>ps</name>
	</parameters>
	
	
	
	<edges>
		<group>0</group>
		<source>startnode</source>
		<target>c1_node</target>
	</edges>
	<edges>
		<group>0</group>
		<source>c1_node</source>
		<target>c1_vals</target>
	</edges>
	
	<edges>
		<group>0</group>
		<source>startnode</source>
		<target>c2_node</target>
	</edges>
	<edges>
		<group>0</group>
		<source>c2_node</source>
		<target>c2_vals</target>
	</edges>
	
	<edges>
		<group>0</group>
		<source>startnode</source>
		<target>c3_node</target>
	</edges>
	<edges>
		<group>0</group>
		<source>c3_node</source>
		<target>c3_vals</target>
	</edges>
	
	<edges>
		<group>0</group>
		<source>startnode</source>
		<target>ps_node</target>
	</edges>
	<edges>
		<group>0</group>
		<source>ps_node</source>
		<target>ps_vals</target>
	</edges>
</parameterspace>
